version: '1.0'

services:
  mcp-server:
    build: pip install -r requirements.txt
    command: ["venv/Scripts/python.exe", "-u", "mcp_server.py"]
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://localhost:11434
      - OLLAMA_MODEL=flujo-mistral:tools
